/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutComponent: typeof import('./components/AboutComponent.vue')['default']
    ActionButton: typeof import('./components/ActionButton.vue')['default']
    ContactNav: typeof import('./components/ContactNav.vue')['default']
    CriteriaComponent: typeof import('./components/CriteriaComponent.vue')['default']
    Divider: typeof import('./components/Divider.vue')['default']
    FAQComponent: typeof import('./components/FAQComponent.vue')['default']
    FooterComponent: typeof import('./components/FooterComponent.vue')['default']
    HeaderComponent: typeof import('./components/HeaderComponent.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    MaterialSymbolsAdd: typeof import('~icons/material-symbols/add')['default']
    MaterialSymbolsAddRounded: typeof import('~icons/material-symbols/add-rounded')['default']
    MaterialSymbolsKeyboardArrowDown: typeof import('~icons/material-symbols/keyboard-arrow-down')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NavButton: typeof import('./components/NavButton.vue')['default']
    PrivacyComponent: typeof import('./components/PrivacyComponent.vue')['default']
    RegisterNav: typeof import('./components/RegisterNav.vue')['default']
    RewardComponent: typeof import('./components/RewardComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RulesComponent: typeof import('./components/RulesComponent.vue')['default']
    SponsorComponent: typeof import('./components/SponsorComponent.vue')['default']
    TimeLineComponent: typeof import('./components/TimeLineComponent.vue')['default']
    TimeLineObject: typeof import('./components/TimeLineObject.vue')['default']
  }
}
